---
- name: IPA server pre-work
  hosts: ipaserver
  become: yes

  handlers:
    - import_tasks: handlers/oelabox-dns/main.yml

  tasks:
    - name: /etc/hosts
      ansible.builtin.copy:
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
          192.168.121.11 ipa.oelabox.local ipa
      notify: restart_networkmanager

- name: Provision Oela Box IPA server
  hosts: ipaserver
  become: true

  vars_files:
    - vars/oelabox-ipa/ipa/common.yml
    - vars/oelabox-ipa/ipa/ipaserver.yml

  handlers:
    - import_tasks: handlers/oelabox-ipa/main.yml

  pre_tasks:
    - name: Perform domain pre-work
      ansible.builtin.import_tasks: tasks/oelabox-ipa/domain-prework.yml

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present

  post_tasks:
    - name: Turn on reverse zone syncing
      freeipa.ansible_freeipa.ipadnsconfig:
        ipaadmin_password: '{{ ipaadmin_password }}'
        allow_sync_ptr: true

    - name: Configure recursion for private nets
      ansible.builtin.import_tasks: tasks/oelabox-ipa/dns-ext.yml
...
